Separa el front-end de la API
IslasGECI/tablero_api pull request #1
Opened 2019-08-06 21:59 UTC by evaristor

Dividí el repo **tablero** en dos repos:

- [tablero_front](http://islasgeci.org:5000/)
- [tableto_api](http://islasgeci.org:500/api/v1/dashboard)

Estos son los cambios mínimos necesarios para lograr la separación.

2019-08-07 23:10 UTC, efren-cabrera requested changes

2019-08-07 23:10 UTC, efren-cabrera commented on requirements.txt
> +requests
Aquí no necesitas `requests`

2019-08-07 23:10 UTC, efren-cabrera commented on templates/index.html
Este archivo no se usa aquí, deberías eliminarlo

2019-08-07 23:10 UTC, efren-cabrera commented on tablero/__init__.py
> +from .Dashboard import get_dashboard
Aquí te falta una línea nueva al final del archivo

2019-08-07 23:10 UTC, efren-cabrera commented on api.py
>  from flask import Flask, jsonify, render_template, request
Aquí no usas `jsonify`, `render_template` ni `request`

2019-08-16 06:41 UTC, evaristor commented on requirements.txt
> +requests
Ya lo quité

2019-08-16 06:41 UTC, evaristor commented on templates/index.html
Listo

2019-08-16 06:41 UTC, evaristor commented on tablero/__init__.py
> +from .Dashboard import get_dashboard
Ya la agregué

2019-08-16 06:44 UTC, evaristor commented on api.py
>  from flask import Flask, jsonify, render_template, request
`jsonify` y `request` los uso en la línea 17: `return jsonify(request.args)`
`render_template` ya lo quité

2019-08-27 18:13 UTC, efren-cabrera requested changes

2019-08-27 18:13 UTC, efren-cabrera commented on tablero/io/read_records.py
> +import numpy as np
Aquí no usas numpy

2019-08-27 18:13 UTC, efren-cabrera commented on .travis.yml
> +  - pip install --editable .
Esto está interesante, no lo conocía

2019-08-27 18:13 UTC, efren-cabrera commented on .travis.yml
> +  - codecov
Te falto agregar una línea nueva al final

2019-08-27 19:10 UTC, devarops commented on .travis.yml
> +  - codecov
:heavy_check_mark:

2019-08-27 19:10 UTC, devarops commented on tablero/io/read_records.py
> +import numpy as np
:heavy_check_mark:

2019-08-28 22:43 UTC, efren-cabrera approved these changes

2019-08-29 15:30 UTC, merged