⚗️🔒️ Implementa token de seguridad
IslasGECI/tablero_api pull request #8
Opened 2021-06-04 19:38 UTC by xwalls

El objetivo es proteger nuestra API mediante un token que funciona como una llave. 
Esto esta relacionado con #6

2021-07-21 22:40 UTC, MaritzaB requested changes
Quiubo @xwalls, dejé algunas sugerencias para el README.
Sé que mas bien era otra cosa la revisión, pero ya que andaba leyendolo hice algunas sugerencias jeje.

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +# Configurar la variable __$TABLERO_API_SECRET_KEY__
Qué te parece la siguiente opción para que siga con nuestra [guía de estílo de shell](https://google.github.io/styleguide/shellguide.html#s7.2-variable-names) 😉 :

```suggestion
# Configurar la variable __`${TABLERO_API_SECRET_KEY}`__
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +variable de entorno en el __~/.vault/.secrets__ está disponible:
```suggestion
variable de entorno en el __`~/.vault/.secrets`__ está disponible:
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +variable de entorno en el __~/.vault/.secrets__ está disponible:
Crees que valga la pena poner como abrir el secrets jajaja 👉👈 es que ahí me atoré 😓 .
```bash
$ cat ~/.vault/.secrets
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +Esta variable es el token de seguridad para nuestra API, sera la llave y debera ser solicidata y configurada por quienes deseen utilizar nuestra API. De no tenerla configurada, deberemos solicitar el
```suggestion
Esta variable es el token de seguridad para nuestra API, será la llave y deberá ser solicitada y configurada por quienes deseen utilizar nuestra API. De no tenerla configurada, deberemos solicitar el _token_ al encargado actual del
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +repositorio y agregarla a nuestro archivo __~/.vault/.secrets__.
```suggestion
repositorio y agregarla a nuestro archivo __`~/.vault/.secrets`__.
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +source ~/.vault/.secrets
```suggestion
$ source ~/.vault/.secrets
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +docker build --tag islasgeci/tablero_api:latest .
```suggestion
$ docker build --tag islasgeci/tablero_api:latest .
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +docker run --detach --publish  500:5000 --rm --env="TABLERO_API_SECRET_KEY=${TABLERO_API_SECRET_KEY}" --volume tablero_api_vol:/workdir/data islasgeci/tablero_api:latest
```suggestion
$ docker run --detach --publish  500:5000 --rm --env="TABLERO_API_SECRET_KEY=${TABLERO_API_SECRET_KEY}" --volume tablero_api_vol:/workdir/data islasgeci/tablero_api:latest
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +docker run --detach --publish  500:5000 --rm --env="TABLERO_API_SECRET_KEY=${TABLERO_API_SECRET_KEY}" --volume tablero_api_vol:/workdir/data islasgeci/tablero_api:latest
```suggestion
$ docker pull islasgeci/tablero_api:latest
$ docker run --detach --publish  500:5000 --rm --env="TABLERO_API_SECRET_KEY=${TABLERO_API_SECRET_KEY}" --volume tablero_api_vol:/workdir/data islasgeci/tablero_api:latest
```

2021-07-21 22:40 UTC, MaritzaB commented on README.md
> +curl -i --header "Authorization: <TABLERO_API_SECRET_KEY>" -X POST "localhost:500/api/v1/records?analista=minombre"
```suggestion
Para probar la API, podemos ejecutar el siguiente comando en nuestra terminal:
```shell
$ curl -i --header "Authorization: <TABLERO_API_SECRET_KEY>" -X POST "localhost:500/api/v1/records?analista=minombre"
```

2021-07-21 23:06 UTC, MaritzaB requested changes

2021-07-21 23:06 UTC, MaritzaB commented on README.md
> +Si desearamos crear un nuevo token podemos ejecutar secuencialmente los siguientes comandos:
Sabes, creo que en esta parte me confundí, porque yo generé un nuevo token y ese que cree lo agregué a mi `.secrets`, y más bien era perdirtelo o no? jajaja
Ya me revolví, es que abajo dice que tenemos que pedirtela... 🤔

2021-07-23 18:24 UTC, xwalls commented on README.md
> +Si desearamos crear un nuevo token podemos ejecutar secuencialmente los siguientes comandos:
perdón, justo es porque aquí hay dos escenarios que representar:
1. Cuando nosotros montamos un "tablero api" y somos el nodo "maestro"
2. Cuando nosotros somos un "súbdito" que quiere utilizar el tablero api que fue montado por el nodo "maestro"

2021-07-23 18:32 UTC, xwalls commented on README.md
> +# Configurar la variable __$TABLERO_API_SECRET_KEY__
gracias!, acepto tu sugerencia. ✌🏽

2021-07-23 18:32 UTC, xwalls commented on README.md
> +variable de entorno en el __~/.vault/.secrets__ está disponible:
gracias!, acepto tu sugerencia. ✌🏽

2021-08-03 18:51 UTC, devarops commented
Excelentes revisiones @MaritzaB. Muchas gracias. Lo voy a aprobar.

2021-08-03 18:54 UTC, devarops approved these changes
![lgtm](https://media.giphy.com/media/Z6f7vzq3iP6Mw/giphy.gif)

2021-08-03 18:54 UTC, closed without merging